@ROOT = https://we-are-reflect.netlify.app/.netlify/functions/index
@PROGRAM = {{ROOT}}/programs

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{PROGRAM}}/test HTTP/1.1

###
POST {{PROGRAM}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "Spartan",
  "description": "Build yourself to become a spartan!",
  "sets": []
}

###
GET {{PROGRAM}}/273664359806272013 HTTP/1.1

###
GET {{PROGRAM}}/all HTTP/1.1

###
PUT {{PROGRAM}}/273664792992940552 HTTP/1.1
Content-Type: application/json

{
  "name": "Spartan",
  "description": "Build yourself to become a spartan!",
  "sets": ["Some exercise group", "and another"]
}