@ROOT = http://localhost:8888/.netlify/functions/index
@EXERCISES = {{ROOT}}/exercises

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{EXERCISES}}/test HTTP/1.1

###
POST {{EXERCISES}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "bench press",
  "description": "",
  "svgId": "bench-press",
  "exerciseGroups": [],
  "sets": [],
  "difficulty": 1
}

###
GET {{EXERCISES}}/273226539989991944 HTTP/1.1

###
PUT {{EXERCISES}}/273577952522797580 HTTP/1.1
Content-Type: application/json

{
  "name": "Bar Deadlift",
  "description": "An exercise to lift a weighted bar from standing position.",
  "svgId": "bar-deadlift",
  "exerciseGroups": ["An exercise group"],
  "sets": [],
  "difficulty": 1
}