@ROOT = http://localhost:8888/.netlify/functions/index
@EXERCISES = {{ROOT}}/exercises

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{EXERCISES}}/test HTTP/1.1

###
POST {{EXERCISES}}/createExercise HTTP/1.1
Content-Type: application/json

{
  "name": "TEST bench press",
  "description": "",
  "svgId": "bench-press",
  "difficulty": 1,
  "exerciseGroup": "chest"
}

###
GET {{EXERCISES}}/getExerciseById/283640056071062028 HTTP/1.1

###
GET {{EXERCISES}}/getExercisesByGroupName HTTP/1.1

###
GET {{EXERCISES}}/getExercisesByGroupName?exerciseGroupName=vertical%20pull HTTP/1.1

###
GET {{EXERCISES}}/getExercisesByGroupName?exerciseGroupName=vertical%20pull&exerciseGroupName=horizontal%20push HTTP/1.1

###
PUT {{EXERCISES}}/updateExerciseById/283640056071062028 HTTP/1.1
Content-Type: application/json

{
  "name": "Weighted pull up",
  "description": "An exercise to help out the trap muscles",
  "svgId": "",
  "difficulty": 1,
  "exerciseGroup": "vertical pull"
}