@ROOT = http://localhost:8888/.netlify/functions/index
@GROUP = {{ROOT}}/exerciseGroup

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{GROUP}}/test HTTP/1.1

###
POST {{GROUP}}/create HTTP/1.1
Content-Type: application/json

{
  "group": "back",
  "description": "",
  "exercises": []
}

###
GET {{GROUP}}/273574032764305928 HTTP/1.1

###
PUT {{GROUP}}/273578167975805448 HTTP/1.1
Content-Type: application/json

{
  "group": "Back",
  "description": "Everything behind you.",
  "exercises": ["exercise"]
}