@ROOT = http://localhost:8888/.netlify/functions/index
@GROUP = {{ROOT}}/meta

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{GROUP}}/test HTTP/1.1

###
GET {{GROUP}}/getGroup/exercise-groups HTTP/1.1
