@ROOT = http://localhost:8888/.netlify/functions/index
@PROGRAM = {{ROOT}}/programs

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{PROGRAM}}/test HTTP/1.1

###
POST {{PROGRAM}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "Athenian",
  "description": "",
  "sets": ["283642537569157644"]
}

###
GET {{PROGRAM}}/284365133684146701 HTTP/1.1

###
GET {{PROGRAM}}/all HTTP/1.1

###
PUT {{PROGRAM}}/284288620916900365 HTTP/1.1
Content-Type: application/json

{
  "name": "Spartan",
  "description": "Build yourself to become a spartan!",
  "sets": ["283639594736419336"]
}