@ROOT = http://localhost:8888/.netlify/functions/index
@SETS = {{ROOT}}/sets

###
GET {{ROOT}}/mainRouterTest HTTP/1.1

###
GET {{SETS}}/test HTTP/1.1

###
POST {{SETS}}/create HTTP/1.1
Content-Type: application/json

{
  "name": "Set 1",
  "description": "Something to do",
  "exerciseGroups": []
}

###
GET {{SETS}}/278664953180717580 HTTP/1.1

###
GET {{SETS}}/all HTTP/1.1

###
PUT {{SETS}}/278664953180717580 HTTP/1.1
Content-Type: application/json

{
  "name": "Set 1",
  "description": "Something to try out...",
  "exerciseGroups": []
}